### ISSUE TITLE
Tab 标题被选择后没有显示了

### ISSUE THREAD

**Issue by Dotila** [Lhcfl/discourse-theme-clean#3]
好像是最近更新过，然后就没显示了。可能是字体调白了

圏住的地方应该有文字的。
![Screenshot_20240801_113735](https://github.com/user-attachments/assets/d2867977-6a35-40d3-bfea-ae40fe1206e1)

**Comment by Lhcfl** [comment]
![IMG_20240801_114824.jpg](https://github.com/user-attachments/assets/156201ec-a87b-4fa3-98cd-0a5edec9afe2)

无法复现，建议考虑一下是不是你论坛的版本较低，或者是不是你论坛上有什么其它不兼容的css

**Comment by Dotila** [comment]
好吧，等我有空升级论坛后再看看。谢谢
